name: 'my first container action'
description: 'Moldova'
author: 'Hov M'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'Green Chisinau'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
